### ISSUE TITLE
Please add Thorium

### ISSUE THREAD

**Issue by hronro** [kawaiier/browserating#11]
Please add [Thorium](https://thorium.rocks/), a Chromium fork focus on performance.

**Comment by kawaiier** [comment]
Thanks for the suggestion. I’ll add it to the next update.

**Comment by kawaiier** [comment]
I've checked Thorium, and it appears the browser hasn't been updated since August, which raises significant security concerns. I will wait before adding it to see if it is still being maintained

**Comment by hronro** [comment]
It is actively maintained, with new commits made every few days:

https://github.com/Alex313031/thorium/commits/main/

I assume you mean it hasn't released a new version in a while? Personally, I'm fine with it being one or two versions behind the official Chromium.
