### ISSUE TITLE
[macOS] Deprecate Intel results and switch to Apple Silicon

### ISSUE THREAD

**Issue by backstab5983** [kawaiier/browserating#5]
I doubt anyone has bought an Intel-based Apple Mac of any kind in the past 4 years. 

I believe it would be more helpful to get results and testing for the Apple Silicon platform! :)

**Comment by kawaiier** [comment]
Thanks for your comment. I'll update the results once macOS Sequoia is released

**Comment by kawaiier** [comment]
Apple Silicon benchmarks were added in the latest update 🎉
