### ISSUE TITLE
Do you consider enabling JIT in browsers that have it disabled by default?

### ISSUE THREAD

**Issue by uazo** [kawaiier/browserating#9]
Beautiful repo, I personally need it for indipendent regression checks.

I was wondering if the tests you did activated JIT or did you leave it as it is in the defaults.
Thanks!

**Comment by kawaiier** [comment]
Thank you! I'm glad you like the repo. Regarding the desktop tests, they were performed with all settings left at their defaults—no changes were made

**Comment by uazo** [comment]
thank you for your reply!

> they were performed with all settings left at their defaults—no changes were made

I imagined this to be the case, given the results.
it would be interesting if you could consider including a test with jit activated.

**Comment by kawaiier** [comment]
Apologies for the delayed response. The primary objective of the entire benchmark is to assess how browsers perform optimally for average users without any additional enhancements. It’s indeed intriguing to observe how they function with JIT, and perhaps that could inspire a separate test that falls outside the scope of Browserating
